#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Format code using yapf
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Install/upgrade dependencies
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

        yapf -ipr tests pycurb
    fi
fi
