#!/bin/bash

set -e

if [[ -n "${CI}" ]]; 
then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Execute project linters and test suites.
"
}

function t() {
    # Lint
    flake8 pycurb tests

    # Code formatting
    yapf -dpr pycurb tests

    # Test suite with coverage enabled
    coverage run --source=pycurb/ -m unittest discover tests/
    coverage xml
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; 
then
    if [ "${1:-}" = "--help" ]; 
    then
        usage
    # use '--local' flag to run in venv locally
    elif [ "${1:-}" = "--local" ];
    then
        python3 -m pip install --user virtualenv
        python3 -m venv env
        source env/bin/activate
        
        t
        
        deactivate
    else
        t
    fi
fi
